defmodule PupWatch.Tapo.Spake2pTest do
  use ExUnit.Case, async: true

  alias PupWatch.Tapo.Spake2p

  # Generated by running pytapo's spake2p.py with fixed inputs.
  @vectors "test/fixtures/tpap_vectors.json" |> File.read!() |> Jason.decode!()

  test "sha256-crypt matches the app's variant" do
    for [password, prefix, expected] <- @vectors["crypt"] do
      assert Spake2p.sha256_crypt(password, prefix) == expected
    end
  end

  test "password_shadow credential transforms" do
    assert Spake2p.apply_extra_crypt("pw", nil) == "pw"

    assert Spake2p.apply_extra_crypt("pw", %{
             "type" => "password_shadow",
             "params" => %{"passwd_id" => 2}
           }) ==
             @vectors["extra_sha1"]

    assert {:error, {:unsupported_extra_crypt, _}} =
             Spake2p.apply_extra_crypt("pw", %{
               "type" => "password_shadow",
               "params" => %{"passwd_id" => 9}
             })
  end

  test "point encoding round-trips and compressed points decode" do
    g = Spake2p.generator()
    assert g |> Spake2p.encode_point() |> Spake2p.decode_point() == g
    <<4, x::binary-32, _::binary>> = Spake2p.encode_point(g)
    # G's y is odd
    assert Spake2p.decode_point(<<3, x::binary>>) == g
    assert Spake2p.add(g, Spake2p.neg(g)) == nil
  end

  test "SPAKE2+ exchange matches pytapo byte for byte" do
    v = @vectors["spake"]
    client = Spake2p.client(v["register"], v["user_random"], v["credential"], v["scalar"])

    assert Base.encode64(client.user_share) == v["user_share"]
    assert Base.encode64(client.user_confirm) == v["user_confirm"]
    assert Base.encode16(client.shared_key, case: :lower) == v["shared_key"]
    assert Spake2p.device_confirm_ok?(client, Base.decode64!(v["dev_confirm"]))
    refute Spake2p.device_confirm_ok?(client, :crypto.strong_rand_bytes(32))

    {key, nonce} = Spake2p.session_key_and_nonce(client.shared_key)
    assert Base.encode16(key, case: :lower) == v["key"]
    assert Base.encode16(nonce, case: :lower) == v["nonce"]
  end
end
