defmodule PupWatch.Repo.Migrations.StorageLimit do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:settings, primary_key: false) do
      add :max_storage_gb, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:recordings) do
      add :size_bytes, :bigint
    end
  end

  def down do
    alter table(:recordings) do
      remove :size_bytes
    end

    drop table(:settings)
  end
end