defmodule PupWatch.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:recordings, primary_key: false) do
      add :peak_confidence, :float, null: false
      add :thumbnail_path, :text, null: false
      add :clip_path, :text, null: false
      add :status, :text, null: false
      add :ended_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:recordings)
  end
end